# Generated by Django 4.2.6 on 2023-11-16 03:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BorrowResource', '0003_borrowresource_approval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowresource',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 23, 3, 28, 30, 708143, tzinfo=datetime.timezone.utc)),
        ),
    ]
