# Generated by Django 4.2.6 on 2023-11-16 06:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAccount', '0003_alter_admin_username_alter_organization_username_and_more'),
        ('BorrowResource', '0005_alter_borrowresource_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowresource',
            name='approval',
            field=models.CharField(choices=[('A', 'Approved'), ('P', 'Pending'), ('R', 'Rejected')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='borrowresource',
            name='org_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CreateAccount.organization'),
        ),
        migrations.AlterField(
            model_name='borrowresource',
            name='resident_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CreateAccount.resident'),
        ),
        migrations.AlterField(
            model_name='borrowresource',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 23, 6, 1, 29, 718652, tzinfo=datetime.timezone.utc)),
        ),
    ]
