# Generated by Django 4.2.6 on 2023-11-16 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BorrowResource', '0009_alter_borrowresource_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowresource',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 23, 14, 10, 36, 286127, tzinfo=datetime.timezone.utc)),
        ),
    ]
