# Generated by Django 4.2.6 on 2023-12-17 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BorrowResource', '0010_alter_borrowresource_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowresource',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 24, 9, 39, 22, 292146, tzinfo=datetime.timezone.utc)),
        ),
    ]
