# Generated by Django 4.2.6 on 2023-10-10 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CreateAccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('complaint_status', models.CharField(choices=[('R', 'Resolved'), ('P', 'Pending'), ('E', 'Escalation')], max_length=1)),
                ('date_of_complaint', models.DateField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateAccount.admin')),
                ('complainant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateAccount.resident')),
            ],
            options={
                'db_table': 'Complaint',
            },
        ),
        migrations.CreateModel(
            name='ComplaintDetails',
            fields=[
                ('complaint_details_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('complaint_type', models.CharField(choices=[('E', 'Environment'), ('R', 'Resident'), ('B', 'Barangay')], max_length=1)),
                ('description', models.TextField()),
                ('complaint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FileComplaint.complaint')),
            ],
        ),
    ]
