# Generated by Django 4.2.6 on 2023-10-10 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CreateAccount', '0001_initial'),
        ('BorrowResource', '0002_initial'),
        ('RequestDocument', '0001_initial'),
        ('OrganizeEvent', '0001_initial'),
        ('BookAppointment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='documents',
            field=models.ManyToManyField(through='RequestDocument.DocumentRequest', to='RequestDocument.document'),
        ),
        migrations.AddField(
            model_name='organization',
            name='borrowed_resources',
            field=models.ManyToManyField(through='BorrowResource.BorrowResource', to='BorrowResource.resource'),
        ),
        migrations.AddField(
            model_name='admin',
            name='approve_appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BookAppointment.appointment'),
        ),
        migrations.AddField(
            model_name='admin',
            name='approve_borrowing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BorrowResource.borrowresource'),
        ),
        migrations.AddField(
            model_name='admin',
            name='approve_doc_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RequestDocument.documentrequest'),
        ),
        migrations.AddField(
            model_name='admin',
            name='approve_event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='OrganizeEvent.event'),
        ),
    ]
